namespace: ksolver

replicaCount: 1

image:
  repository: ghcr.io/syslenslabs/ksolver
  pullPolicy: Always
  tag: latest

nameOverride: solver
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

logLevel: info

extraEnv: []
