apiVersion: v1
kind: Node
metadata:
  name: kwok-gpu-0
  annotations:
    kwok.x-k8s.io/node: fake
    node.alpha.kubernetes.io/ttl: "0"
  labels:
    type: kwok
    ksolver-demo: "true"
    nvidia.com/gpu.product: NVIDIA-RTX-4090
    ksolver.dev/gpu-vram-gib: "24"
spec:
  taints:
  - effect: NoSchedule
    key: kwok.x-k8s.io/node
    value: fake
status:
  allocatable:
    cpu: "32"
    memory: 256Gi
    pods: "110"
    nvidia.com/gpu: "4"
  capacity:
    cpu: "32"
    memory: 256Gi
    pods: "110"
    nvidia.com/gpu: "4"
  nodeInfo:
    architecture: amd64
    kubeletVersion: fake
    operatingSystem: linux
---
apiVersion: v1
kind: Node
metadata:
  name: kwok-gpu-1
  annotations:
    kwok.x-k8s.io/node: fake
    node.alpha.kubernetes.io/ttl: "0"
  labels:
    type: kwok
    ksolver-demo: "true"
    nvidia.com/gpu.product: NVIDIA-RTX-4090
    ksolver.dev/gpu-vram-gib: "24"
spec:
  taints:
  - effect: NoSchedule
    key: kwok.x-k8s.io/node
    value: fake
status:
  allocatable:
    cpu: "32"
    memory: 256Gi
    pods: "110"
    nvidia.com/gpu: "4"
  capacity:
    cpu: "32"
    memory: 256Gi
    pods: "110"
    nvidia.com/gpu: "4"
  nodeInfo:
    architecture: amd64
    kubeletVersion: fake
    operatingSystem: linux
